### ISSUE TITLE
Define baseDir

### ISSUE THREAD

**Issue by Colir** [monolithed/base64-inline-loader#8]
Hi,
i'm looking for a way to set a basedir for that the base64-inline-loader can resolve path.

in my root "src" folder, i've a scss folder with all my scss chunk and at my root "src" i've another folder call "gfx" where i store all my images/icons.

In a scss chunk i call my image like this
`background: url('wave-top.svg') no-repeat top center / 100% auto;`

Of course this didn't work as the loader look at images in the "scss" folder...

Can i resolve this without rewriting all my css calling images ?

Thank you

**Comment by monolithed** [comment]
If you want to modify the path of all assets you can add a plugin which hooks into the file paths like `html-webpack-basepath-plugin`
